apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eks-veve-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "eksSecretVeVe"
          objectType: "secretsmanager"
          objectAlias: eksSecretVeve
  secretObjects:
  - secretName: eksSecretVeve
    type: Opaque
    data:
    - objectName: accesskeyalias
      key: PORT
    - objectName: secretkeyalias
      key: SESSION_SECRET
    - objectName: secretkeyalias
      key: DB_HOST
    - objectName: secretkeyalias
      key: DB_PORT
    - objectName: secretkeyalias
      key: DB_DATABASE
    - objectName: secretkeyalias
      key: DB_USERNAME
    - objectName: secretkeyalias
      key: DB_PASSWORD